[build]
  base    = ""
  command = "npm install && npm run build --workspace=packages/shared && npm run build --workspace=apps/web"
  publish = "apps/web/dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_API_URL = "https://plataforma-de-gesti-n-documental-production.up.railway.app/api"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
